export default {
    configs: {},
    agents: [],
    patients: [],
    recentpatients: [],
    consultations: [],
    emplacements: [],
    patients_pending: [],
    emplacement_pharmacies: [],
    pharmacies: [],
    examens: [],
    all_examens: [],
    labo_examens: [],
    pending_prescriptions: [],
    rcode: "",
};