export default {
  dataLoading: false,
  configs: {},
  agents: [],
  patients: [],
  recentpatients: [],
  consultations: [],
  emplacements: [],
  patients_pending: [],
  emplacement_pharmacies: [],
  pharmacies: [],
  examens: [],
  all_examens: [],
  labo_examens: [],
  pending_prescriptions: [],
  schedules: [],
  all_facturations: [],
  site_facturations: [],
  patient_doc: {},
  rcode: "",
};
